app = "trumptracker-ai"
primary_region = "ord"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"
